<<<<<<< HEAD
# Generated by Django 2.2.4 on 2019-10-24 19:18
=======
# Generated by Django 2.2.4 on 2019-10-15 10:21
>>>>>>> 7e8d6075fd9667b5fd009a5e23a1aa9ae7318a1e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
<<<<<<< HEAD
=======
                ('amount', models.FloatField(default=0)),
>>>>>>> 7e8d6075fd9667b5fd009a5e23a1aa9ae7318a1e
                ('price_reducing', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
