# Generated by Django 2.2.6 on 2019-10-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_remove_voucher_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
