# Generated by Django 2.2.6 on 2019-10-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20191021_1947'),
        ('reviews', '0002_auto_20191016_0935'),
        ('reviews', '0005_review_user'),
    ]

    operations = [
    ]
