# Generated by Django 2.2.6 on 2019-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_merge_20191024_2152'),
    ]

    operations = [
    ]
