# Generated by Django 2.2.6 on 2019-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_user_name'),
    ]

    operations = [
    ]
