# Generated by Django 2.2.4 on 2019-10-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
    ]
