# Generated by Django 2.2.4 on 2019-10-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191020_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.Voucher'),
        ),
    ]
