# Generated by Django 2.2.4 on 2019-09-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190929_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Earning',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
