# Generated by Django 2.2.6 on 2019-10-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191024_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
