# Generated by Django 2.2.4 on 2019-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190928_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
