# Generated by Django 2.2.4 on 2019-09-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190929_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='total',
        ),
    ]
