# Generated by Django 2.2.4 on 2019-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderlineitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
