# Generated by Django 2.2.6 on 2019-10-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191020_1538'),
        ('orders', '0004_auto_20191016_1834'),
    ]

    operations = [
    ]
