# Generated by Django 2.2.6 on 2019-10-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20191024_2152'),
    ]

    operations = [
    ]
