# Generated by Django 2.2.6 on 2019-10-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191024_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='voucher',
            new_name='coupon',
        ),
    ]
