# Generated by Django 2.2.6 on 2019-10-25 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191024_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.CharField(max_length=40, blank=True, null=True, default=''),
        ),
    ]
