# Generated by Django 2.2.4 on 2019-09-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderedproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedProducts',
        ),
    ]
