# Generated by Django 2.2.6 on 2019-10-25 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_voucher_amount'),
        ('orders', '0006_auto_20191024_2152'),
    ]

    operations = [
        
    ]
