# Generated by Django 2.2.6 on 2019-10-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191024_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='voucher',
        ),
    ]
