# Generated by Django 2.2.6 on 2019-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191025_2011'),
    ]

    operations = [
    ]
