# Generated by Django 2.2.6 on 2019-10-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191025_2023 copy'),
        ('orders', '0002_auto_20191025_2030'),
        ('orders', '0008_auto_20191025_2018'),
        ('orders', '0010_auto_20191025_2013'),
    ]

    operations = [
    ]
