# Generated by Django 2.2.6 on 2019-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_merge_20191025_2036'),
    ]

    operations = [

    ]
