# Generated by Django 2.2.4 on 2019-10-10 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('category', models.CharField(blank=True, choices=[('bestseller', 'Bestseller'), ('latest', ' Latest')], max_length=100, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity_sold', models.IntegerField(default=0)),
            ],
        ),
    ]
