# Generated by Django 2.2.4 on 2019-09-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190928_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('bestseller', 'Bestseller'), ('latest', ' Latest')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
